// <auto-generated />
namespace GameLibra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLibraryOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLibraryOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "202012052031461_AddLibraryOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
